### ISSUE TITLE
Error: No challenge found for type 'http-01' and identifier

### ISSUE THREAD

**Issue by JackDPro** [yourivw/LEClient#124]
When i call `verifyPendingOrderAuthorization` with `LEOrder::CHALLENGE_TYPE_HTTP` it return `"message":"No challenge found for type 'http-01' and identifier 'jack.vip'.","code":65,`, but with `LEOrder::CHALLENGE_TYPE_DNS` it will work well.

My code :
```
$email = 'admin@jack.vip';
$domain = 'jack.vip';
$client = new LEClient([$email], LEClient::LE_STAGING, LEClient::LOG_DEBUG, storage_path('userdata/certs/1111/' . $domain));
$order = $client->getOrCreateOrder($domain, [$domain, '*.' . $domain]);
$verify = $order->verifyPendingOrderAuthorization($domain, LEOrder::CHALLENGE_TYPE_DNS); # work
$verify = $order->verifyPendingOrderAuthorization($domain, LEOrder::CHALLENGE_TYPE_HTTP); # not work
```

Debug:
```
27-04-2022 12:28:32, function getLEDirectory (function get):
Array ( [request] => GET https://acme-staging-v02.api.letsencrypt.org/directory [header] => HTTP/2 200 server: nginx date: Wed, 27 Apr 2022 04:28:34 GMT content-type: application/json content-length: 822 cache-control: public, max-age=0, no-cache x-frame-options: DENY strict-transport-security: max-age=604800 [status] => 200 [body] => Array ( [ism6DGvTR3U] => https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417 [keyChange] => https://acme-staging-v02.api.letsencrypt.org/acme/key-change [meta] => Array ( [caaIdentities] => Array ( [0] => letsencrypt.org ) [termsOfService] => https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf [website] => https://letsencrypt.org/docs/staging-environment/ ) [newAccount] => https://acme-staging-v02.api.letsencrypt.org/acme/new-acct [newNonce] => https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce [newOrder] => https://acme-staging-v02.api.letsencrypt.org/acme/new-order [renewalInfo] => https://acme-staging-v02.api.letsencrypt.org/get/draft-aaron-ari/renewalInfo/ [revokeCert] => https://acme-staging-v02.api.letsencrypt.org/acme/revoke-cert ) )

27-04-2022 12:28:33, function getNewNonce (function head):
Array ( [request] => HEAD https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce [header] => HTTP/2 200 server: nginx date: Wed, 27 Apr 2022 04:28:35 GMT cache-control: public, max-age=0, no-cache link: ;rel="index" replay-nonce: 0001mW8J0Ne6juK1RvNTUH4g0-RT8o0UMVf2jy6B7BSq9I4 x-frame-options: DENY strict-transport-security: max-age=604800 [status] => 200 [body] => )

27-04-2022 12:28:34, function getLEAccount (function post):
Array ( [request] => POST https://acme-staging-v02.api.letsencrypt.org/acme/new-acct [header] => HTTP/2 200 server: nginx date: Wed, 27 Apr 2022 04:28:36 GMT content-type: application/json content-length: 889 boulder-requester: 52220104 cache-control: public, max-age=0, no-cache link: ;rel="index" location: https://acme-staging-v02.api.letsencrypt.org/acme/acct/52220104 replay-nonce: 0002SYNziDbmsY76qclHIZ0vSchqoberr48pEM-MZJn7Hn8 x-frame-options: DENY strict-transport-security: max-age=604800 [status] => 200 [body] => Array ( [key] => Array ( [kty] => RSA [n] => rcUsLtMZn4royULElRGeP-MH90f3UTHsuuioOA194HMmSLlzE6vDu5zEULXqtJ2DZJO31vUdIXZ9MduQzg6EGbpZ7XXWGlu6B7OgG2T310sowsD2fF-j7h4SL4pkWZGhFmTXNFMScBUQ5Jqj8aqKWH13n8igi8yHPU9NLvSfT_p5Xu9XNwxzym-MruvwOxX6_JBhhrSpwSChPGFW2DTI6Z9GlLSfzEKeyzCr7xS2j75viY15z_XNUgmTY9BOcjxu8F7wOYuGl8hcnJhcrI1qXsRQZYXJ1dC2Aff5AEBktKaGtX2SyP8VBCsM5Zpp1UrcBa0CysRfflKWbJlK_TLV1K5PAc3ZJjAwgfFae31fTc4waaqaUXRrH5rJPoDG4djNYUxyZTuijyXBEA04hQEtA5nkxFVTixjXEJGUiJnKkrQfjedUYCWbRX1f31cwHqUbAnzNqfkEoWB6Y0Vvs8DkIo-QAhYZ0IFFozs6KsZr6WUcwIapBweXeDz-7ISx4M7pWsrLxYwHJ3YEsqa8hI9SGfl9zuY9TdUNdalxTx1mXNohj3FZ6uBg-femI_aV_kqWEnjv7V7X_hg_LB5Mt8np2q_uSzw25KzRh5mnFvCsRuuehbX46M-oYdJRlKpXWf7MQ_e6izDBOdtDxJm1pEKPVq1HA9cOZh7LPYjcj1L0Q7E [e] => AQAB ) [contact] => Array ( [0] => mailto:admin@jack.vip ) [initialIp] => 103.164.81.226 [createdAt] => 2022-04-27T04:27:16Z [status] => valid ) )

27-04-2022 12:28:35, function getLEAccountData (function post):
Array ( [request] => POST https://acme-staging-v02.api.letsencrypt.org/acme/acct/52220104 [header] => HTTP/2 200 server: nginx date: Wed, 27 Apr 2022 04:28:37 GMT content-type: application/json content-length: 889 boulder-requester: 52220104 cache-control: public, max-age=0, no-cache link: ;rel="index" link: ;rel="terms-of-service" replay-nonce: 00026qu0Qt2-OQx1h6IzH94Q2NNFTO7XQw2iGCX4Ym93r74 x-frame-options: DENY strict-transport-security: max-age=604800 [status] => 200 [body] => Array ( [key] => Array ( [kty] => RSA [n] => rcUsLtMZn4royULElRGeP-MH90f3UTHsuuioOA194HMmSLlzE6vDu5zEULXqtJ2DZJO31vUdIXZ9MduQzg6EGbpZ7XXWGlu6B7OgG2T310sowsD2fF-j7h4SL4pkWZGhFmTXNFMScBUQ5Jqj8aqKWH13n8igi8yHPU9NLvSfT_p5Xu9XNwxzym-MruvwOxX6_JBhhrSpwSChPGFW2DTI6Z9GlLSfzEKeyzCr7xS2j75viY15z_XNUgmTY9BOcjxu8F7wOYuGl8hcnJhcrI1qXsRQZYXJ1dC2Aff5AEBktKaGtX2SyP8VBCsM5Zpp1UrcBa0CysRfflKWbJlK_TLV1K5PAc3ZJjAwgfFae31fTc4waaqaUXRrH5rJPoDG4djNYUxyZTuijyXBEA04hQEtA5nkxFVTixjXEJGUiJnKkrQfjedUYCWbRX1f31cwHqUbAnzNqfkEoWB6Y0Vvs8DkIo-QAhYZ0IFFozs6KsZr6WUcwIapBweXeDz-7ISx4M7pWsrLxYwHJ3YEsqa8hI9SGfl9zuY9TdUNdalxTx1mXNohj3FZ6uBg-femI_aV_kqWEnjv7V7X_hg_LB5Mt8np2q_uSzw25KzRh5mnFvCsRuuehbX46M-oYdJRlKpXWf7MQ_e6izDBOdtDxJm1pEKPVq1HA9cOZh7LPYjcj1L0Q7E [e] => AQAB ) [contact] => Array ( [0] => mailto:admin@jack.vip ) [initialIp] => 103.164.81.226 [createdAt] => 2022-04-27T04:27:16Z [status] => valid ) )

27-04-2022 12:28:35, function LEClient __construct:
LEClient finished constructing

27-04-2022 12:28:37, function __construct (function post):
Array ( [request] => POST https://acme-staging-v02.api.letsencrypt.org/acme/order/52220104/2417070664 [header] => HTTP/2 200 server: nginx date: Wed, 27 Apr 2022 04:28:38 GMT content-type: application/json content-length: 483 cache-control: public, max-age=0, no-cache link: ;rel="index" replay-nonce: 0002rkRhfSPilfVsLvRLt_kv0RCGGbtILDvA-pWur5YzI9Y x-frame-options: DENY strict-transport-security: max-age=604800 [status] => 200 [body] => Array ( [status] => pending [expires] => 2022-05-04T04:27:18Z [identifiers] => Array ( [0] => Array ( [type] => dns [value] => *.jack.vip ) [1] => Array ( [type] => dns [value] => jack.vip ) ) [authorizations] => Array ( [0] => https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/2293668524 [1] => https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/2293668534 ) [finalize] => https://acme-staging-v02.api.letsencrypt.org/acme/finalize/52220104/2417070664 ) )

27-04-2022 12:28:38, function __construct (function post):
Array ( [request] => POST https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/2293668524 [header] => HTTP/2 200 server: nginx date: Wed, 27 Apr 2022 04:28:39 GMT content-type: application/json content-length: 388 boulder-requester: 52220104 cache-control: public, max-age=0, no-cache link: ;rel="index" replay-nonce: 0001HeeOFw-mww45JN6iPCYDrGBk_F2_Uq-gjp_CI9Ujk08 x-frame-options: DENY strict-transport-security: max-age=604800 [status] => 200 [body] => Array ( [identifier] => Array ( [type] => dns [value] => jack.vip ) [status] => pending [expires] => 2022-05-04T04:27:18Z [challenges] => Array ( [0] => Array ( [type] => dns-01 [status] => pending [url] => https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/2293668524/_J1RSg [token] => iko4-0aAmZub_6PiinwCtjV91ctuczOwazUFLhnZ3D4 ) ) [wildcard] => 1 ) )

27-04-2022 12:28:39, function __construct (function post):
Array ( [request] => POST https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/2293668534 [header] => HTTP/2 200 server: nginx date: Wed, 27 Apr 2022 04:28:41 GMT content-type: application/json content-length: 810 boulder-requester: 52220104 cache-control: public, max-age=0, no-cache link: ;rel="index" replay-nonce: 00024lipL4tCl3VHUYFadFNj5Vo2TGBdKK0dmBX0oDWkT58 x-frame-options: DENY strict-transport-security: max-age=604800 [status] => 200 [body] => Array ( [identifier] => Array ( [type] => dns [value] => jack.vip ) [status] => pending [expires] => 2022-05-04T04:27:18Z [challenges] => Array ( [0] => Array ( [type] => http-01 [status] => pending [url] => https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/2293668534/usZ2DQ [token] => 2quqqwxuZV8eQrH8YnMjH_16yu9oOlbXpaq5qCb082o ) [1] => Array ( [type] => dns-01 [status] => pending [url] => https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/2293668534/QdGDng [token] => 2quqqwxuZV8eQrH8YnMjH_16yu9oOlbXpaq5qCb082o ) [2] => Array ( [type] => tls-alpn-01 [status] => pending [url] => https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/2293668534/XM4vvA [token] => 2quqqwxuZV8eQrH8YnMjH_16yu9oOlbXpaq5qCb082o ) ) ) )

{"message":"No challenge found for type 'http-01' and identifier 'jack.vip'.","code":65,"status_code":500,"debug":{"line":44,"file":"\/var\/www\/tucana-tls-api\/vendor\/yourivw\/leclient\/src\/Exceptions\/LEAuthorizationException.php","class":"LEClient\\Exceptions\\LEAuthorizationException","trace":["#0 \/var\/www\/tucana-tls-api\/vendor\/yourivw\/leclient\/src\/LEAuthorization.php(123): LEClient\\Exceptions\\LEAuthorizationException::NoChallengeFoundException('http-01', 'jack.vip')","#1 \/var\/www\/tucana-tls-api\/vendor\/yourivw\/leclient\/src\/LEOrder.php(433): LEClient\\LEAuthorization->getChallenge('http-01')","#2 \/var\/www\/tucana-tls-api\/app\/Http\/Controllers\/Test\/TestController.php(24): LEClient\\LEOrder->verifyPendingOrderAuthorization('jack.vip', 'http-01')","#3 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Controller.php(54): App\\Http\\Controllers\\Test\\TestController->test()","#4 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('test', Array)","#5 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php(262): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\Test\\TestController), 'test')","#6 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php(205): Illuminate\\Routing\\Route->runController()","#7 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(721): Illuminate\\Routing\\Route->run()","#8 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))","#9 \/var\/www\/tucana-tls-api\/vendor\/fruitcake\/laravel-cors\/src\/HandleCors.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#10 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#11 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Middleware\/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#12 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#13 \/var\/www\/tucana-tls-api\/app\/Http\/Middleware\/ChangeLocale.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#14 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): App\\Http\\Middleware\\ChangeLocale->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#15 \/var\/www\/tucana-tls-api\/vendor\/dingo\/api\/src\/Http\/Middleware\/PrepareController.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#16 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Dingo\\Api\\Http\\Middleware\\PrepareController->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#17 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#18 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(723): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#19 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(698): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Dingo\\Api\\Http\\Request))","#20 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(662): Illuminate\\Routing\\Router->runRoute(Object(Dingo\\Api\\Http\\Request), Object(Illuminate\\Routing\\Route))","#21 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(651): Illuminate\\Routing\\Router->dispatchToRoute(Object(Dingo\\Api\\Http\\Request))","#22 \/var\/www\/tucana-tls-api\/vendor\/dingo\/api\/src\/Routing\/Adapter\/Laravel.php(88): Illuminate\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))","#23 \/var\/www\/tucana-tls-api\/vendor\/dingo\/api\/src\/Routing\/Router.php(518): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')","#24 \/var\/www\/tucana-tls-api\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(126): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))","#25 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(128): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))","#26 \/var\/www\/tucana-tls-api\/vendor\/fruitcake\/laravel-cors\/src\/HandleCors.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#27 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#28 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#29 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#30 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#31 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#32 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#33 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#34 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#35 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#36 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#37 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#38 \/var\/www\/tucana-tls-api\/vendor\/fruitcake\/laravel-cors\/src\/HandleCors.php(52): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#39 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#40 \/var\/www\/tucana-tls-api\/vendor\/fideloper\/proxy\/src\/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#41 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Fideloper\\Proxy\\TrustProxies->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#42 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Http\/Middleware\/TrustHosts.php(48): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#43 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Illuminate\\Http\\Middleware\\TrustHosts->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#44 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#45 \/var\/www\/tucana-tls-api\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#46 \/var\/www\/tucana-tls-api\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))","#47 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(167): Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#48 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))","#49 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#50 \/var\/www\/tucana-tls-api\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))","#51 \/var\/www\/tucana-tls-api\/public\/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))","#52 {main}"]}}
```

**Comment by TheRealSimpleSimon** [comment]
I believe HTTP-01 support was dropped by Lets Encrypt maybe years ago.
However, if you override the API server name (it's an argumennt to  the LEClient class constructor I think), maybe you can still use the OLD API.

**Comment by JackDPro** [comment]
@TheRealSimpleSimon Thank you . I found it.
