### ISSUE TITLE
Updates for version 1.1.5 fails work

### ISSUE THREAD

**Issue by politsin** [yourivw/LEClient#62]
```
Server: nginx
Link: <https://acme-v02.api.letsencrypt.org/directory>;rel="index"
Replay-Nonce: 91BH0jpueGqlKWhWCDzlXMOGR3B4RKCE-7OuJGAfAzc
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Content-Length: 0
Expires: Mon, 25 Mar 2019 14:19:12 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Mon, 25 Mar 2019 14:19:12 GMT
Connection: keep-alive

 in /var/www/html/vendor/yourivw/leclient/src/LEConnector.php:147
Stack trace:
#0 /var/www/html/vendor/yourivw/leclient/src/LEConnector.php(196): LEClient\LEConnector->request('HEAD', 'https://acme-v0...')
#1 /var/www/html/vendor/yourivw/leclient/src/LEConnector.php(91): LEClient\LEConnector->head('https://acme-v0...')
#2 /var/www/html/vendor/yourivw/leclient/src/LEConnector.php(70): LEClient\LEConnector->getNewNonce()
#3 /var/www/html/vendor/yourivw/leclient/src/LEClient.php(156): LEClient\LEConnector->__construct(1, 'https://acme-v0...', Array)
#4 /var/www/html/modules/synapse/letsencrypt/src/Service/LetsEncrypt.php(113): LEClient\LEClient->__construct(Array, 'https://acme-v0...', 1, Array, Array)
#5 /var/www/html/modules/custom/city/city.drush.inc(64): Drupal\letsencrypt\Service\LetsEncrypt->sign('****.****', Array)
```

**Comment by politsin** [comment]
it was api problems
